services:
  postgres:
    image: postgres:18
    container_name: lab5_recsys_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: recsys_lab5
    ports:
      - "5433:5432"
    volumes:
      - lab5_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recsys_lab5"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  lab5_postgres_data:
